services:
  imap-netflix-household-automation:
    container_name: imap-netflix-household-automation
    image: "mcr.microsoft.com/playwright:v1.44.0-jammy"
    working_dir: /app
    ipc: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/app
    command: /bin/sh -c "yarn install && yarn start"
    stdin_open: true
